import './style.css';
import * as pdfjsLib from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import * as mupdf from 'mupdf';
pdfjsLib.GlobalWorkerOptions.workerSrc = workerUrl;

const app=document.querySelector('#app');
app.innerHTML=`<header><b>Osama Automation Test</b><span class="sub">Radiology workflow toolkit • local-first</span><div class="appTabs"><button class="appTab active" data-app-tab="pdf">PDF Editor</button><button class="appTab" data-app-tab="templates">Email Templates</button><button class="appTab" data-app-tab="tasks">Daily Tasks</button><button class="appTab" data-app-tab="links">Quick Links</button><button class="appTab" data-app-tab="notes">Quick Notes</button><button class="appTab" data-app-tab="queue">Work Queue</button><button class="appTab" data-app-tab="composer">Email Composer</button><button class="appTab" data-app-tab="handover">Handover</button><button class="appTab" data-app-tab="home">Dashboard</button></div><div class="globalTools"><input id="globalSearch" placeholder="Search workspace…" aria-label="Search workspace"><button id="themeToggle" title="Toggle dark mode">◐</button><button id="compactToggle" title="Toggle compact mode">↔</button></div><div id="pdfHeaderActions"><label class="open">Open PDF<input id="pdfInput" type="file" accept="application/pdf" hidden></label><button id="save" disabled>Save PDF</button></div></header>
<div class="shell" id="pdfPanel"><aside>
<button data-tool="edit" class="active">↖ Edit existing</button><button data-tool="text">T Add text</button><button data-tool="whiteout">▭ Whiteout</button><button data-tool="rect">□ Box</button><button data-tool="check">✓ Check</button><button data-tool="xmark">✕ X</button><button data-tool="radio">● Radio</button>
<button id="addImage">▧ Signature / image</button><input id="imageInput" type="file" accept="image/png,image/jpeg" hidden>
<hr><b>Editing</b><label class="switch"><input id="existingText" type="checkbox" checked> Existing text clickable</label><label class="switch"><input id="nativeFields" type="checkbox" checked> Native form fields</label><div id="info" class="mini">Open a PDF.</div>
<hr><b>Signature presets</b><input id="sigSearch" class="sideInput" placeholder="Search signatures"><div id="presets"></div><button id="savePreset">+ Save signature preset</button>
<hr><b>Selected object</b>
<div id="selectedType" class="mini">Nothing selected</div>
<div id="textControls" class="selectedControls" hidden><label>Text size <div class="numberRow"><button id="fontMinus" title="Smaller text">−</button><input id="fontSize" type="number" min="5" max="96" step="1"><button id="fontPlus" title="Larger text">+</button></div></label></div>
<div id="imageControls" class="selectedControls" hidden><label>Signature size <div class="sizeGrid"><span>W</span><input id="objWidth" type="number" min="5" step="1"><span>H</span><input id="objHeight" type="number" min="5" step="1"></div></label><label class="switch"><input id="lockAspect" type="checkbox" checked> Lock proportions</label></div>
<div id="moveControls" class="selectedControls" hidden><span class="mini">Move selected</span><div class="nudge"><span></span><button data-nudge="0,-1" title="Move up">↑</button><span></span><button data-nudge="-1,0" title="Move left">←</button><button data-nudge="0,1" title="Move down">↓</button><button data-nudge="1,0" title="Move right">→</button></div></div>
<button id="duplicate">Duplicate selected</button><button id="fit">Fit text to box</button><button id="delete">Delete selected</button><div class="row"><button id="undo">↶ Undo</button><button id="redo">↷ Redo</button></div>
<div class="help"><b>Shortcuts:</b> Ctrl/Cmd+Z undo • Ctrl/Cmd+Shift+Z redo • Ctrl/Cmd+C/V duplicate • Ctrl/Cmd+S save • Delete remove.<br><br><b>Edit position/size:</b> click an added/replaced text or signature. Drag it to move; drag the blue corner to resize. Text size can also be changed from the sidebar. Arrow keys nudge the selected object; Shift+Arrow moves 10 points.<br><br><b>Fit to box:</b> select text and toggle Fit text to box.<br><br><b>Privacy:</b> PDFs stay in this browser. Recovery data is stored locally on this device only.</div>
</aside><main id="pdfMain"><div id="empty"><h2>Open a PDF</h2><p>Edit fields directly, click printed text to replace it, or add signatures and annotations.</p></div><div id="workspace" hidden><nav id="thumbs"></nav><div id="stageWrap"><div id="stage"><canvas id="pdfCanvas"></canvas><div id="interaction"></div><div id="overlay"></div></div></div></div></main></div>
<section id="homePanel" class="modulePanel" hidden><div class="moduleTop"><div><h1>Dashboard</h1><p>Your local-first work hub. Avoid patient-identifiable information in tasks and notes.</p></div><div class="moduleActions"><button id="exportBackup">Export Backup</button><label class="open">Import Backup<input id="importBackup" type="file" accept="application/json" hidden></label></div></div><div id="dashboardGrid" class="dashboardGrid"></div></section>
<section id="tasksPanel" class="modulePanel" hidden><div class="moduleTop"><div><h1>Daily Tasks</h1><p>Plan the shift, tick work off, and carry unfinished items forward.</p></div><button id="addTask" class="primary">+ Add Task</button></div><div id="taskProgress" class="progressCard"></div><div class="moduleToolbar"><select id="taskFilter"><option value="pending">Pending</option><option value="all">All</option><option value="done">Done</option></select><input id="taskSearch" placeholder="Search tasks…"><button id="carryTasks">Carry pending to today</button><button id="clearDone">Clear completed</button></div><div id="taskList" class="stackList"></div></section>
<section id="linksPanel" class="modulePanel" hidden><div class="moduleTop"><div><h1>Quick Links</h1><p>Keep frequently used work resources in one place.</p></div><button id="addLink" class="primary">+ Add Link</button></div><div class="moduleToolbar"><input id="linkSearch" placeholder="Search links…"></div><div id="linkList" class="linkGrid"></div></section>
<section id="notesPanel" class="modulePanel" hidden><div class="moduleTop"><div><h1>Quick Notes</h1><p>Temporary non-patient notes saved on this device.</p></div><div class="moduleActions"><button id="copyNotes">⧉ Copy</button><button id="clearNotes" class="dangerText">Clear</button></div></div><textarea id="quickNotes" class="notesArea" placeholder="Temporary notes only - do not store patient-identifiable information here."></textarea><div id="notesStatus" class="mini"></div></section>
<section id="templatesPanel" class="modulePanel" hidden><div class="templatesTop"><div><h1>Email Templates</h1><p>Save reusable replies locally, edit them anytime, and copy a ready-to-send version.</p></div><button id="addTemplate" class="primary">+ Add Template</button></div><div class="templateToolbar"><input id="templateSearch" placeholder="Search templates…"><select id="templateCategory"><option value="">All categories</option></select><label><input id="favoritesOnly" type="checkbox"> Favorites only</label></div><div id="templateCards" class="templateCards"></div></section>

<section id="queuePanel" class="modulePanel" hidden><div class="moduleTop"><div><h1>Radiology Work Queue</h1><p>Track operational requests without using the inbox as a task list. Do not enter patient-identifiable information unless your organisation approves this storage.</p></div><button id="addCase" class="primary">+ Add Case</button></div><div id="queueStats" class="progressCard"></div><div class="moduleToolbar"><input id="queueSearch" placeholder="Search cases…"><select id="queueStatus"><option value="">All statuses</option><option>New</option><option>Need Info</option><option>Ready to Book</option><option>Booked</option><option>External Referral</option><option>Waiting</option><option>Completed</option></select><select id="queuePriority"><option value="">All priorities</option><option>Normal</option><option>Urgent</option></select><button id="showDue">Due / overdue</button></div><div id="queueList" class="stackList"></div></section>
<section id="composerPanel" class="modulePanel" hidden><div class="moduleTop"><div><h1>Email Composer</h1><p>Build a reply from a saved template or reusable snippet, preview it, then copy the subject or body.</p></div><button id="addSnippet" class="primary">+ Add Snippet</button></div><div class="composerGrid"><div class="composerSide"><label>Template<select id="composerTemplate"><option value="">Choose template…</option></select></label><label>Subject<input id="composerSubject" placeholder="Email subject"></label><div id="composerFields"></div><h3>Snippets</h3><div id="snippetList"></div></div><div class="composerMain"><label>Preview<textarea id="composerPreview" rows="18" placeholder="Choose a template or type here…"></textarea></label><div class="moduleActions"><button id="copySubject">⧉ Copy Subject</button><button id="copyBody" class="primary">⧉ Copy Email</button><button id="clearComposer">Clear</button></div></div></div></section>
<section id="handoverPanel" class="modulePanel" hidden><div class="moduleTop"><div><h1>Shift Handover</h1><p>Generate a summary from the local queue and daily tasks. Review it before sharing.</p></div><div class="moduleActions"><button id="generateHandover" class="primary">Generate</button><button id="copyHandover">⧉ Copy</button></div></div><textarea id="handoverText" class="notesArea" placeholder="Generate a handover summary…"></textarea></section>
<div id="caseModal" class="modal" hidden><div class="modalCard"><div class="modalHead"><h2 id="caseModalTitle">Add Case</h2><button data-close="caseModal" class="iconBtn">×</button></div><label>Reference / description<input id="caseTitle" maxlength="140" placeholder="Use a non-identifying reference unless approved"></label><div class="twoCols"><label>Status<select id="caseStatus"><option>New</option><option>Need Info</option><option>Ready to Book</option><option>Booked</option><option>External Referral</option><option>Waiting</option><option>Completed</option></select></label><label>Priority<select id="casePriority"><option>Normal</option><option>Urgent</option></select></label></div><div class="twoCols"><label>Owner<input id="caseOwner" maxlength="60" placeholder="Initials / team member"></label><label>Modality<select id="caseModality"><option>General</option><option>X-Ray</option><option>Ultrasound</option><option>CT</option><option>MRI</option><option>Other</option></select></label></div><label>Follow-up date/time<input id="caseFollowup" type="datetime-local"></label><label>Notes<textarea id="caseNotes" rows="3" placeholder="Operational notes only"></textarea></label><label>Workflow checklist<select id="caseChecklistType"><option value="">None</option><option value="external">External CT/MRI referral</option><option value="booking">Booking request</option></select></label><div class="modalActions"><button data-close="caseModal">Cancel</button><button id="saveCase" class="primary">Save Case</button></div></div></div>
<div id="snippetModal" class="modal" hidden><div class="modalCard small"><div class="modalHead"><h2 id="snippetModalTitle">Add Snippet</h2><button data-close="snippetModal" class="iconBtn">×</button></div><label>Name<input id="snippetName" maxlength="80"></label><label>Text<textarea id="snippetBody" rows="5"></textarea></label><div class="modalActions"><button data-close="snippetModal">Cancel</button><button id="saveSnippet" class="primary">Save Snippet</button></div></div></div>
<div id="searchModal" class="modal" hidden><div class="modalCard"><div class="modalHead"><h2>Workspace Search</h2><button data-close="searchModal" class="iconBtn">×</button></div><div id="searchResults" class="stackList"></div></div></div>
<div id="pdfCheckModal" class="modal" hidden><div class="modalCard small"><div class="modalHead"><h2>Pre-save review</h2><button data-close="pdfCheckModal" class="iconBtn">×</button></div><p class="mini">Confirm the items relevant to this document. This is a human check, not clinical validation.</p><label class="checkLine"><input type="checkbox" class="pdfReview"> Patient/document details checked</label><label class="checkLine"><input type="checkbox" class="pdfReview"> Examination / scan checked</label><label class="checkLine"><input type="checkbox" class="pdfReview"> Payment / referral details checked if applicable</label><label class="checkLine"><input type="checkbox" class="pdfReview"> Signature / marks checked if applicable</label><div class="modalActions"><button data-close="pdfCheckModal">Cancel</button><button id="confirmPdfSave" class="primary">Save PDF</button></div></div></div>
<div id="taskModal" class="modal" hidden><div class="modalCard small"><div class="modalHead"><h2 id="taskModalTitle">Add Task</h2><button data-close="taskModal" class="iconBtn">×</button></div><label>Task<input id="taskTitle" maxlength="160" placeholder="e.g. Check outstanding MRI referrals"></label><label>Priority<select id="taskPriority"><option>Normal</option><option>Urgent</option></select></label><label>Optional time<input id="taskTime" type="time"></label><label class="switch"><input id="taskRecurring" type="checkbox"> Repeat every day</label><label>Notes<textarea id="taskNotes" rows="3" placeholder="No patient-identifiable information"></textarea></label><div class="modalActions"><button data-close="taskModal">Cancel</button><button id="saveTask" class="primary">Save Task</button></div></div></div>
<div id="linkModal" class="modal" hidden><div class="modalCard small"><div class="modalHead"><h2 id="linkModalTitle">Add Link</h2><button data-close="linkModal" class="iconBtn">×</button></div><label>Name<input id="linkName" maxlength="80" placeholder="e.g. RIS / PACS"></label><label>URL<input id="linkUrl" type="url" placeholder="https://..."></label><label class="switch"><input id="linkFavorite" type="checkbox"> Favorite</label><div class="modalActions"><button data-close="linkModal">Cancel</button><button id="saveLink" class="primary">Save Link</button></div></div></div>
<div id="templateModal" class="modal" hidden><div class="modalCard"><div class="modalHead"><h2 id="templateModalTitle">Add Template</h2><button id="closeTemplateModal" class="iconBtn">×</button></div><label>Template name<input id="tplName" maxlength="80" placeholder="e.g. Appointment confirmation"></label><label>Category<input id="tplCategory" maxlength="40" list="categorySuggestions" placeholder="e.g. Booking"><datalist id="categorySuggestions"></datalist></label><label>Email text<textarea id="tplBody" rows="10" placeholder="Write your email template here…"></textarea></label><div class="placeholderHelp">Optional placeholders: <code>{{patient_name}}</code>, <code>{{scan}}</code>, <code>{{date}}</code>, <code>{{time}}</code>.</div><div class="modalActions"><button id="cancelTemplate">Cancel</button><button id="saveTemplate" class="primary">Save Template</button></div></div></div>
<footer id="pdfFooter"><button id="toggleThumbs">☰ Pages</button><button id="prev">←</button><span id="pageInfo">No PDF</span><button id="next">→</button><button id="zoomOut">−</button><span id="zoomLabel">100%</span><button id="zoomIn">+</button></footer>`;
const $=s=>document.querySelector(s);let pdf=null,pdfBytes=null,pageNum=1,zoom=1.15,objects=[],selected=null,tool='edit',pageData=new Map(),formEdits=new Map(),token=0,history=[],future=[],clipboardObj=null,currentFile=null,dirty=false,recoveryKey=null;
const stage=$('#stage'),canvas=$('#pdfCanvas'),interaction=$('#interaction'),overlay=$('#overlay');
const esc=s=>(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pageObjects=()=>objects.filter(o=>o.page===pageNum);
function select(el){document.querySelectorAll('.obj.selected').forEach(x=>x.classList.remove('selected'));selected=el;if(el)el.classList.add('selected');const o=selected?objects.find(x=>x.id===selected.dataset.id):null;const isText=!!o&&['text','replaceText'].includes(o.type),isImage=o?.type==='image';$('#fit').disabled=!isText;$('#duplicate').disabled=!o;$('#delete').disabled=!o;$('#fit').textContent=o?.fitToBox?'✓ Fit to box ON':'Fit text to box';$('#selectedType').textContent=o?(isText?'Text selected':isImage?'Signature / image selected':o.type+' selected'):'Nothing selected';$('#textControls').hidden=!isText;$('#imageControls').hidden=!isImage;$('#moveControls').hidden=!o;if(isText)$('#fontSize').value=Math.round((o.fontSize||16)*10)/10;if(isImage){$('#objWidth').value=Math.round(o.w*10)/10;$('#objHeight').value=Math.round(o.h*10)/10;$('#lockAspect').checked=o.lockAspect!==false}}
function snapshot(){return JSON.stringify({objects,formEdits:[...formEdits]})}
function pushHistory(){history.push(snapshot());if(history.length>80)history.shift();future=[]}
function restore(s){if(!s)return;const d=JSON.parse(s);objects=d.objects||[];formEdits=new Map(d.formEdits||[]);dirty=true;drawInteraction();drawObjects();saveRecovery()}
function markDirty(){dirty=true;saveRecovery()}
function undo(){if(!history.length)return;future.push(snapshot());restore(history.pop())}
function redo(){if(!future.length)return;history.push(snapshot());restore(future.pop())}
function saveRecovery(){if(!recoveryKey||!dirty)return;try{localStorage.setItem(recoveryKey,JSON.stringify({objects,formEdits:[...formEdits],savedAt:Date.now()}))}catch(e){console.warn('Recovery save failed',e)}}
async function inspectPage(page,vp){const tc=await page.getTextContent(),anns=await page.getAnnotations({intent:'display'});const pieces=[];for(const item of tc.items){if(!item.str?.trim())continue;const tx=pdfjsLib.Util.transform(vp.transform,item.transform),fontPx=Math.max(7,Math.hypot(tx[2],tx[3]));const st=tc.styles?.[item.fontName]||{};pieces.push({str:item.str,x:tx[4],y:tx[5]-fontPx,w:Math.max(3,item.width*zoom),h:fontPx*1.12,fontSize:fontPx/zoom,fontFamily:st.fontFamily||'Helvetica',bold:/bold/i.test((item.fontName||'')+' '+(st.fontFamily||''))});}
// Merge adjacent PDF text pieces on the same baseline so clicks feel like Acrobat lines/fields.
pieces.sort((a,b)=>Math.abs(a.y-b.y)<3?a.x-b.x:a.y-b.y);const lines=[];for(const p of pieces){let last=lines.at(-1);if(last&&Math.abs(last.y-p.y)<Math.max(3,p.h*.25)&&p.x-(last.x+last.w)<Math.max(14,p.h*1.2)){last.str+=(p.x-(last.x+last.w)>2?' ':'')+p.str;last.w=Math.max(last.w,p.x+p.w-last.x);last.h=Math.max(last.h,p.h);last.fontSize=Math.max(last.fontSize,p.fontSize);last.bold=last.bold||p.bold}else lines.push({...p});}
const fields=anns.filter(a=>a.subtype==='Widget').map(a=>{const r=vp.convertToViewportRectangle(a.rect);return{id:a.id,name:a.fieldName||'',type:a.fieldType||'',value:a.fieldValue??'',options:a.options||[],checkBox:!!a.checkBox,radioButton:!!a.radioButton,buttonValue:a.buttonValue||a.exportValue||'',x:Math.min(r[0],r[2]),y:Math.min(r[1],r[3]),w:Math.abs(r[2]-r[0]),h:Math.abs(r[3]-r[1])}});pageData.set(pageNum,{lines,fields});}
async function render(){if(!pdf)return;const t=++token,page=await pdf.getPage(pageNum),vp=page.getViewport({scale:zoom});if(t!==token)return;canvas.width=vp.width;canvas.height=vp.height;for(const e of [canvas,interaction,overlay,stage]){e.style.width=vp.width+'px';e.style.height=vp.height+'px'}await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;await inspectPage(page,vp);drawInteraction();drawObjects();$('#pageInfo').textContent=`Page ${pageNum} / ${pdf.numPages}`;$('#zoomLabel').textContent=Math.round(zoom/1.15*100)+'%'}
function drawInteraction(){interaction.innerHTML='';const d=pageData.get(pageNum)||{lines:[],fields:[]};$('#info').textContent=`${d.lines.length} editable text areas • ${d.fields.length} native fields`;
if($('#existingText').checked)d.lines.forEach((x,i)=>{const hit=document.createElement('button');hit.className='textHit';hit.title='Click to edit: '+x.str;Object.assign(hit.style,{left:x.x+'px',top:x.y+'px',width:Math.max(8,x.w)+'px',height:Math.max(10,x.h)+'px'});hit.onclick=e=>{e.stopPropagation();if(tool==='edit')editLine(x,i)};interaction.appendChild(hit)});
if($('#nativeFields').checked)d.fields.forEach(drawField)}
function editLine(x,i){let o=objects.find(o=>o.type==='replaceText'&&o.page===pageNum&&o.sourceIndex===i);if(!o)o=addObj('replaceText',x.x/zoom,x.y/zoom,{w:Math.max(45,x.w/zoom),h:Math.max(15,x.h/zoom),sourceW:Math.max(45,x.w/zoom),sourceH:Math.max(15,x.h/zoom),fontSize:Math.max(7,x.fontSize),fontFamily:x.fontFamily||'Helvetica',bold:!!x.bold,text:x.str,sourceIndex:i,sourceX:x.x/zoom,sourceY:x.y/zoom,fitToBox:false});const el=overlay.querySelector(`[data-id="${o.id}"]`);select(el);const input=el?.querySelector('textarea');if(input){input.focus();input.select()}}
const fkey=f=>`${pageNum}:${f.name||f.id}`;
function drawField(f){const key=fkey(f),current=formEdits.has(key)?formEdits.get(key):f.value;let el;if(f.type==='Btn'&&f.radioButton){el=document.createElement('input');el.type='radio';el.className='nativeField radio';el.name='radio_'+(f.name||f.id);el.checked=String(current)===String(f.buttonValue)||current===true;el.onchange=()=>{if(el.checked){pushHistory();formEdits.set(key,f.buttonValue||'Yes');markDirty()}}}else if(f.type==='Btn'){el=document.createElement('input');el.type='checkbox';el.className='nativeField checkbox';el.checked=!!current&&current!=='Off';el.onchange=()=>{pushHistory();formEdits.set(key,el.checked);markDirty()}}else if(f.type==='Ch'&&f.options?.length){el=document.createElement('select');el.className='nativeField';for(const op of f.options){const opt=document.createElement('option');opt.value=op.exportValue??op.displayValue??op;opt.textContent=op.displayValue??op.exportValue??op;el.appendChild(opt)}el.value=current||'';el.onchange=()=>{pushHistory();formEdits.set(key,el.value);markDirty()}}else{el=document.createElement('input');el.type='text';el.className='nativeField';el.value=current||'';el.onchange=()=>{pushHistory();formEdits.set(key,el.value);markDirty()}}el.title=f.name||'PDF field';Object.assign(el.style,{left:f.x+'px',top:f.y+'px',width:Math.max(12,f.w)+'px',height:Math.max(12,f.h)+'px'});interaction.appendChild(el)}
function addObj(type,x=60,y=60,extra={}){pushHistory();const o={id:crypto.randomUUID(),page:pageNum,type,x,y,w:(type==='text'||type==='replaceText')?170:type==='image'?140:36,h:(type==='text'||type==='replaceText')?28:type==='image'?60:30,fontSize:16,fitToBox:false,...extra};objects.push(o);markDirty();const el=createObj(o);select(el);return o}
function drawObjects(){overlay.innerHTML='';selected=null;pageObjects().forEach(createObj)}
function createObj(o){const el=document.createElement('div');el.className='obj '+o.type;el.dataset.id=o.id;Object.assign(el.style,{left:o.x*zoom+'px',top:o.y*zoom+'px',width:o.w*zoom+'px',height:o.h*zoom+'px'});if(o.type==='text'||o.type==='replaceText'){el.innerHTML=`<textarea class="inlineText" rows="1" spellcheck="false">${esc(o.text)}</textarea><i class="handle"></i>`;el.style.fontSize=o.fontSize*zoom+'px'}else if(o.type==='whiteout'||o.type==='rect')el.innerHTML='<i class="handle"></i>';else if(o.type==='check'||o.type==='xmark'||o.type==='radio'){el.innerHTML=`<span>${o.type==='check'?'✓':o.type==='xmark'?'✕':'●'}</span><i class="handle"></i>`;el.style.fontSize=o.fontSize*zoom+'px'}else if(o.type==='image')el.innerHTML=`<img src="${o.src}"><i class="handle"></i>`;overlay.appendChild(el);wire(el,o);return el}
function wire(el,o){const input=el.querySelector('.inlineText');if(input){
  const autoGrow=()=>{o.text=input.value;const probe=document.createElement('span');probe.className='textProbe';probe.style.fontSize=(o.fontSize*zoom)+'px';probe.textContent=input.value||' ';document.body.appendChild(probe);const minW=(o.sourceW||45)*zoom;const wanted=o.fitToBox?minW:Math.max(minW,probe.getBoundingClientRect().width+12);probe.remove();const lines=Math.max(1,(input.value.match(/\n/g)||[]).length+1);const wantedH=Math.max((o.sourceH||15)*zoom,lines*o.fontSize*zoom*1.25+6);o.w=wanted/zoom;o.h=wantedH/zoom;el.style.width=wanted+'px';el.style.height=wantedH+'px';input.style.width='100%';input.style.height='100%'};
  let beforeText=null;input.oninput=()=>{autoGrow();markDirty()};input.onfocus=()=>{select(el);el.classList.add('typing');beforeText=snapshot()};input.onblur=()=>{el.classList.remove('typing');if(beforeText&&beforeText!==snapshot()){history.push(beforeText);future=[];markDirty()}beforeText=null};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();input.blur()}};setTimeout(autoGrow,0)
}
el.addEventListener('pointerdown',e=>{if(e.target.matches('input,.handle'))return;select(el);const before=snapshot();let sx=e.clientX,sy=e.clientY,ox=o.x,oy=o.y;el.setPointerCapture(e.pointerId);const mv=v=>{o.x=ox+(v.clientX-sx)/zoom;o.y=oy+(v.clientY-sy)/zoom;el.style.left=o.x*zoom+'px';el.style.top=o.y*zoom+'px'},up=()=>{if(before!==snapshot()){history.push(before);future=[];markDirty()}el.removeEventListener('pointermove',mv);el.removeEventListener('pointerup',up)};el.addEventListener('pointermove',mv);el.addEventListener('pointerup',up)});const h=el.querySelector('.handle');h?.addEventListener('pointerdown',e=>{e.stopPropagation();select(el);const before=snapshot();let sx=e.clientX,sy=e.clientY,ow=o.w,oh=o.h;h.setPointerCapture(e.pointerId);const mv=v=>{o.w=Math.max(12,ow+(v.clientX-sx)/zoom);o.h=o.type==='image'&&o.aspect&&o.lockAspect!==false?o.w/o.aspect:Math.max(12,oh+(v.clientY-sy)/zoom);el.style.width=o.w*zoom+'px';el.style.height=o.h*zoom+'px'},up=()=>{if(before!==snapshot()){history.push(before);future=[];markDirty()}h.removeEventListener('pointermove',mv);h.removeEventListener('pointerup',up)};h.addEventListener('pointermove',mv);h.addEventListener('pointerup',up)})}
function detectPrintedBox(screenX,screenY){try{const ctx=canvas.getContext('2d',{willReadFrequently:true}),R=Math.round(22*zoom),cx=Math.round(screenX),cy=Math.round(screenY),x0=Math.max(0,cx-R),y0=Math.max(0,cy-R),x1=Math.min(canvas.width-1,cx+R),y1=Math.min(canvas.height-1,cy+R),im=ctx.getImageData(x0,y0,x1-x0+1,y1-y0+1),W=im.width,H=im.height;const dark=(x,y)=>{const k=(y*W+x)*4;return (im.data[k]+im.data[k+1]+im.data[k+2])/3<145};const vscore=x=>{let n=0;for(let y=0;y<H;y++)if(dark(x,y))n++;return n/H},hscore=y=>{let n=0;for(let x=0;x<W;x++)if(dark(x,y))n++;return n/W};let vs=[],hs=[];for(let x=0;x<W;x++)if(vscore(x)>.28)vs.push(x);for(let y=0;y<H;y++)if(hscore(y)>.28)hs.push(y);const L=vs.filter(x=>x<=cx-x0).at(-1),RR=vs.find(x=>x>=cx-x0),T=hs.filter(y=>y<=cy-y0).at(-1),B=hs.find(y=>y>=cy-y0);if(L==null||RR==null||T==null||B==null)return null;const w=RR-L,h=B-T;if(w<6*zoom||h<6*zoom||w>28*zoom||h>28*zoom||Math.abs(w-h)>Math.max(w,h)*.45)return null;return{x:(x0+L+1)/zoom,y:(y0+T+1)/zoom,w:Math.max(8,(w-2)/zoom),h:Math.max(8,(h-2)/zoom)}}catch{return null}}
overlay.addEventListener('pointerdown',e=>{if(e.target!==overlay)return;select(null);const r=overlay.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top,x=sx/zoom,y=sy/zoom;if(tool==='text'){const o=addObj('text',x,y,{text:''});setTimeout(()=>overlay.querySelector(`[data-id="${o.id}"] textarea`)?.focus())}else if(tool==='whiteout')addObj('whiteout',x,y,{w:150,h:26});else if(tool==='rect')addObj('rect',x,y,{w:150,h:38});else if(['check','xmark','radio'].includes(tool)){const box=detectPrintedBox(sx,sy);addObj(tool,box?.x??x-7,box?.y??y-7,{w:box?.w??14,h:box?.h??14,fontSize:12})}});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));overlay.style.pointerEvents=tool==='edit'?'none':'auto';interaction.classList.toggle('editing',tool==='edit')});overlay.style.pointerEvents='none';interaction.classList.add('editing');
$('#existingText').onchange=drawInteraction;$('#nativeFields').onchange=drawInteraction;
function selectedObject(){return selected?objects.find(x=>x.id===selected.dataset.id):null}
function refreshSelectedObject(id){drawObjects();const el=overlay.querySelector(`[data-id="${id}"]`);if(el)select(el)}
function changeSelected(mutator){const o=selectedObject();if(!o)return;pushHistory();mutator(o);markDirty();refreshSelectedObject(o.id)}
function setFontSize(value){const n=Math.max(5,Math.min(96,Number(value)||5));changeSelected(o=>{if(['text','replaceText'].includes(o.type)){o.fontSize=n;if(!o.fitToBox)o.h=Math.max(o.sourceH||15,n*1.35)}})}
$('#fontSize').onchange=e=>setFontSize(e.target.value);$('#fontMinus').onclick=()=>{const o=selectedObject();if(o)setFontSize((o.fontSize||16)-1)};$('#fontPlus').onclick=()=>{const o=selectedObject();if(o)setFontSize((o.fontSize||16)+1)};
$('#lockAspect').onchange=e=>{const o=selectedObject();if(o?.type==='image'){pushHistory();o.lockAspect=e.target.checked;markDirty();select(selected)}};
$('#objWidth').onchange=e=>{const n=Math.max(5,Number(e.target.value)||5);changeSelected(o=>{if(o.type!=='image')return;o.w=n;if(o.aspect&&o.lockAspect!==false)o.h=o.w/o.aspect})};
$('#objHeight').onchange=e=>{const n=Math.max(5,Number(e.target.value)||5);changeSelected(o=>{if(o.type!=='image')return;o.h=n;if(o.aspect&&o.lockAspect!==false)o.w=o.h*o.aspect})};
document.querySelectorAll('[data-nudge]').forEach(b=>b.onclick=()=>{const [dx,dy]=b.dataset.nudge.split(',').map(Number);changeSelected(o=>{o.x+=dx;o.y+=dy})});

async function openPDFFile(f){if(!f)return;currentFile=f;pdfBytes=new Uint8Array(await f.arrayBuffer());pdf=await pdfjsLib.getDocument({data:pdfBytes.slice()}).promise;pageNum=1;objects=[];formEdits.clear();pageData.clear();history=[];future=[];dirty=false;recoveryKey='pdf-editor-recovery:'+encodeURIComponent(f.name)+':'+f.size+':'+f.lastModified;$('#empty').hidden=true;$('#workspace').hidden=false;$('#save').disabled=false;await render();renderThumbnails();const saved=localStorage.getItem(recoveryKey);if(saved&&confirm('A local unsaved editing session was found for this PDF. Restore it?')){try{const d=JSON.parse(saved);objects=d.objects||[];formEdits=new Map(d.formEdits||[]);dirty=true;drawInteraction();drawObjects()}catch{}}}$('#pdfInput').onchange=e=>openPDFFile(e.target.files[0]);
$('#prev').onclick=()=>{if(pdf&&pageNum>1){pageNum--;render()}};$('#next').onclick=()=>{if(pdf&&pageNum<pdf.numPages){pageNum++;render()}};$('#zoomIn').onclick=()=>{if(pdf){zoom=Math.min(2.5,zoom+.15);render()}};$('#zoomOut').onclick=()=>{if(pdf){zoom=Math.max(.5,zoom-.15);render()}};$('#delete').onclick=()=>{if(!selected)return;pushHistory();objects=objects.filter(o=>o.id!==selected.dataset.id);selected.remove();selected=null;markDirty()};$('#undo').onclick=undo;$('#redo').onclick=redo;$('#duplicate').onclick=()=>duplicateSelected();$('#fit').onclick=()=>{if(!selected)return;const o=objects.find(x=>x.id===selected.dataset.id);if(!o||!['text','replaceText'].includes(o.type))return;pushHistory();o.fitToBox=!o.fitToBox;markDirty();drawObjects();const el=overlay.querySelector(`[data-id="${o.id}"]`);select(el);$('#fit').textContent=o.fitToBox?'✓ Fit to box ON':'Fit text to box'};
const dataURL=file=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});async function addImageFile(file){const src=await dataURL(file),img=new Image();img.onload=()=>{let w=150,h=w*img.height/img.width;if(h>110){h=110;w=h*img.width/img.height}addObj('image',60,60,{src,w,h,aspect:img.width/img.height,lockAspect:true})};img.src=src}$('#addImage').onclick=()=>$('#imageInput').click();$('#imageInput').onchange=e=>{if(e.target.files[0])addImageFile(e.target.files[0]);e.target.value=''};
const SIG_DB='pdf-editor-signatures-v1',SIG_STORE='signatures';
function sigDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(SIG_DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(SIG_STORE))db.createObjectStore(SIG_STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function sigAll(){const db=await sigDB();return new Promise((resolve,reject)=>{const r=db.transaction(SIG_STORE,'readonly').objectStore(SIG_STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
async function sigPut(x){const db=await sigDB();return new Promise((resolve,reject)=>{const r=db.transaction(SIG_STORE,'readwrite').objectStore(SIG_STORE).put(x);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
async function sigDelete(id){const db=await sigDB();return new Promise((resolve,reject)=>{const r=db.transaction(SIG_STORE,'readwrite').objectStore(SIG_STORE).delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
async function showPresets(){let p=await sigAll();const q=($('#sigSearch')?.value||'').trim().toLowerCase();p.sort((a,b)=>(b.lastUsed||b.createdAt||0)-(a.lastUsed||a.createdAt||0));if(q)p=p.filter(x=>x.name.toLowerCase().includes(q));$('#presets').innerHTML=p.length?p.map(x=>`<div class="preset"><button data-p="${x.id}" class="sigPick"><img src="${x.src}"><span>${esc(x.name)}</span></button><button data-r="${x.id}" title="Rename">✎</button><button data-d="${x.id}" title="Delete">×</button></div>`).join(''):'<small>No saved presets</small>';document.querySelectorAll('[data-p]').forEach(b=>b.onclick=async()=>{const x=(await sigAll()).find(v=>v.id===b.dataset.p);if(!x)return;x.lastUsed=Date.now();await sigPut(x);const img=new Image();img.onload=()=>{let w=150,h=w*img.height/img.width;if(h>110){h=110;w=h*img.width/img.height}addObj('image',60,60,{src:x.src,w,h,aspect:img.width/img.height,lockAspect:true,presetId:x.id})};img.src=x.src;showPresets()});document.querySelectorAll('[data-r]').forEach(b=>b.onclick=async()=>{const x=(await sigAll()).find(v=>v.id===b.dataset.r);if(!x)return;const name=prompt('Signature name:',x.name);if(name?.trim()){x.name=name.trim();await sigPut(x);showPresets()}});document.querySelectorAll('[data-d]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this saved signature?')){await sigDelete(b.dataset.d);showPresets()}})}
$('#sigSearch').oninput=showPresets;
$('#savePreset').onclick=()=>{const i=document.createElement('input');i.type='file';i.accept='image/png,image/jpeg';i.onchange=async()=>{if(!i.files[0])return;const name=prompt('Signature name:',i.files[0].name.replace(/\.[^.]+$/,''));if(!name?.trim())return;const src=await dataURL(i.files[0]);await sigPut({id:crypto.randomUUID(),name:name.trim(),src,createdAt:Date.now()});await showPresets()};i.click()};showPresets();
async function applyFields(doc){let form;try{form=doc.getForm()}catch{return}for(const [key,val] of formEdits){const name=key.slice(key.indexOf(':')+1);let f;try{f=form.getField(name)}catch{continue}try{const n=f.constructor.name;if(n.includes('CheckBox'))val?f.check():f.uncheck();else if(n.includes('RadioGroup'))f.select(String(val));else if(n.includes('Dropdown')||n.includes('OptionList'))f.select(String(val));else if(n.includes('TextField'))f.setText(String(val))}catch(e){console.warn(name,e)}}try{form.updateFieldAppearances(await doc.embedFont(StandardFonts.Helvetica))}catch{}}
async function removeOriginalTextContent(inputBytes){
  // MuPDF redaction can remove ONLY text while explicitly preserving images and line art.
  // This is the key difference from V5: no white rectangle is painted over the field.
  const replacements=objects.filter(o=>o.type==='replaceText');
  if(!replacements.length)return inputBytes.slice();
  let mdoc;
  try{
    mdoc=mupdf.Document.openDocument(inputBytes.slice(), 'application/pdf');
    const pdfDoc=mdoc.asPDF();
    const byPage=new Map();
    for(const o of replacements){if(!byPage.has(o.page))byPage.set(o.page,[]);byPage.get(o.page).push(o)}
    for(const [pageNo,items] of byPage){
      const page=pdfDoc.loadPage(pageNo-1);
      for(const o of items){
        // Tight rectangle around the original detected text only. MuPDF coordinates use
        // a top-left origin, matching the editor coordinates.
        const padX=Math.min(0.8, Math.max(0.15,(o.fontSize||10)*0.035));
        const padY=Math.min(0.5, Math.max(0.10,(o.fontSize||10)*0.025));
        const sourceX=o.sourceX??o.x, sourceY=o.sourceY??o.y;
        const x0=Math.max(0,sourceX-padX), y0=Math.max(0,sourceY-padY);
        const x1=sourceX+(o.sourceW||o.w)+padX, y1=sourceY+(o.sourceH||o.h)+padY;
        const red=page.createAnnotation('Redact');
        red.setRect([x0,y0,x1,y1]);
        red.update();
      }
      // Preserve images and line art (box borders, grey fills, blue rules); remove text only.
      page.applyRedactions(
        false,
        mupdf.PDFPage.REDACT_IMAGE_NONE,
        mupdf.PDFPage.REDACT_LINE_ART_NONE,
        mupdf.PDFPage.REDACT_TEXT_REMOVE
      );
      page.destroy();
    }
    const out=pdfDoc.saveToBuffer('garbage,compress').asUint8Array();
    return new Uint8Array(out);
  }catch(err){
    console.error('Direct text removal failed',err);
    throw new Error('This PDF could not be edited at content level. No file was changed. '+(err?.message||err));
  }finally{try{mdoc?.destroy()}catch{}}
}
$('#save').onclick=async()=>{if(!pdfBytes)return;let cleaned;try{cleaned=await removeOriginalTextContent(pdfBytes)}catch(err){alert(err.message);return}const doc=await PDFDocument.load(cleaned),font=await doc.embedFont(StandardFonts.Helvetica),boldFont=await doc.embedFont(StandardFonts.HelveticaBold);await applyFields(doc);for(const o of objects){const p=doc.getPage(o.page-1),H=p.getHeight();if(o.type==='whiteout')p.drawRectangle({x:o.x,y:H-o.y-o.h,width:o.w,height:o.h,color:rgb(1,1,1)});if(o.type==='rect')p.drawRectangle({x:o.x,y:H-o.y-o.h,width:o.w,height:o.h,borderColor:rgb(0,0,0),borderWidth:1});if(o.type==='text'||o.type==='replaceText'){const useFont=o.bold?boldFont:font;let fs=o.fontSize;if(o.fitToBox&&o.w>4){const lines=(o.text||'').split('\n');for(const line of lines){const width=useFont.widthOfTextAtSize(line||' ',fs);if(width>o.w-4)fs=Math.max(5,fs*(o.w-4)/width)}}p.drawText(o.text||'',{x:o.x,y:H-o.y-fs,size:fs,font:useFont,color:rgb(0,0,0),maxWidth:o.fitToBox?o.w:undefined,lineHeight:fs*1.1})}if(o.type==='check'){
  // Draw a true checkmark as vector strokes. Do not use a Unicode glyph:
  // PDF standard fonts can substitute unsupported glyphs during export.
  const left=o.x, bottom=H-o.y-o.h, w=o.w, h=o.h;
  const thickness=Math.max(1,Math.min(w,h)*0.085);
  p.drawLine({start:{x:left+w*0.16,y:bottom+h*0.48},end:{x:left+w*0.39,y:bottom+h*0.24},thickness,color:rgb(0,0,0)});
  p.drawLine({start:{x:left+w*0.39,y:bottom+h*0.24},end:{x:left+w*0.86,y:bottom+h*0.80},thickness,color:rgb(0,0,0)});
}if(o.type==='xmark'){const left=o.x,bottom=H-o.y-o.h,w=o.w,h=o.h,t=Math.max(1,Math.min(w,h)*0.075);p.drawLine({start:{x:left+w*.2,y:bottom+h*.2},end:{x:left+w*.8,y:bottom+h*.8},thickness:t,color:rgb(0,0,0)});p.drawLine({start:{x:left+w*.2,y:bottom+h*.8},end:{x:left+w*.8,y:bottom+h*.2},thickness:t,color:rgb(0,0,0)})}if(o.type==='radio'){const left=o.x,bottom=H-o.y-o.h,w=o.w,h=o.h;p.drawEllipse({x:left+w/2,y:bottom+h/2,xScale:w*.24,yScale:h*.24,color:rgb(0,0,0)})}if(o.type==='image'){const bytes=await fetch(o.src).then(r=>r.arrayBuffer());let im;try{im=await doc.embedPng(bytes)}catch{im=await doc.embedJpg(bytes)}p.drawImage(im,{x:o.x,y:H-o.y-o.h,width:o.w,height:o.h})}}const out=await doc.save(),blob=new Blob([out],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(currentFile?.name||'document.pdf').replace(/\.pdf$/i,'')+'_edited.pdf';a.click();dirty=false;if(recoveryKey)localStorage.removeItem(recoveryKey);setTimeout(()=>URL.revokeObjectURL(url),1000)};
function duplicateSelected(){if(!selected)return;const o=objects.find(x=>x.id===selected.dataset.id);if(!o)return;pushHistory();const copy=structuredClone(o);copy.id=crypto.randomUUID();copy.x+=12;copy.y+=12;objects.push(copy);markDirty();drawObjects();select(overlay.querySelector(`[data-id="${copy.id}"]`))}
async function renderThumbnails(){const nav=$('#thumbs');nav.innerHTML='';if(!pdf)return;for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),vp=page.getViewport({scale:.18});const c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;await page.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;const b=document.createElement('button');b.className='thumb';b.dataset.page=n;b.appendChild(c);const sp=document.createElement('span');sp.textContent=n;b.appendChild(sp);b.onclick=()=>{pageNum=n;render();document.querySelectorAll('.thumb').forEach(x=>x.classList.toggle('current',+x.dataset.page===n))};nav.appendChild(b)}document.querySelector('.thumb')?.classList.add('current')}
$('#toggleThumbs').onclick=()=>$('#thumbs').classList.toggle('hidden');
const main=document.querySelector('main');['dragenter','dragover'].forEach(ev=>main.addEventListener(ev,e=>{e.preventDefault();main.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>main.addEventListener(ev,e=>{e.preventDefault();main.classList.remove('dragging')}));main.addEventListener('drop',e=>{const f=[...e.dataTransfer.files].find(x=>x.type==='application/pdf'||/\.pdf$/i.test(x.name));if(f)openPDFFile(f)});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
window.addEventListener('keydown',e=>{const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();if(pdf)$('#save').click();return}if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(mod&&e.key.toLowerCase()==='c'&&selected&&!['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)){const o=objects.find(x=>x.id===selected.dataset.id);if(o)clipboardObj=structuredClone(o);return}if(mod&&e.key.toLowerCase()==='v'&&clipboardObj&&!['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();pushHistory();const o=structuredClone(clipboardObj);o.id=crypto.randomUUID();o.page=pageNum;o.x+=12;o.y+=12;objects.push(o);markDirty();drawObjects();select(overlay.querySelector(`[data-id="${o.id}"]`));return}if(selected&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&!['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();const o=selectedObject();if(o){const step=e.shiftKey?10:1,before=snapshot();if(e.key==='ArrowLeft')o.x-=step;if(e.key==='ArrowRight')o.x+=step;if(e.key==='ArrowUp')o.y-=step;if(e.key==='ArrowDown')o.y+=step;history.push(before);future=[];markDirty();refreshSelectedObject(o.id)}return}if((e.key==='Delete'||e.key==='Backspace')&&selected&&!['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();$('#delete').click()}});

// Email Templates module
const TEMPLATE_KEY='osama-automation-email-templates-v1';let editingTemplateId=null;
function loadTemplates(){try{return JSON.parse(localStorage.getItem(TEMPLATE_KEY)||'[]')}catch{return []}}
function saveTemplates(items){localStorage.setItem(TEMPLATE_KEY,JSON.stringify(items))}
const APP_TABS=['pdf','templates','tasks','links','notes','queue','composer','handover','home'];
function setAppTab(name){
  if(!APP_TABS.includes(name)) name='pdf';
  const isPdf=name==='pdf';
  const pdfPanel=$('#pdfPanel'), pdfFooter=$('#pdfFooter'), pdfActions=$('#pdfHeaderActions');
  if(pdfPanel){pdfPanel.hidden=!isPdf;pdfPanel.classList.toggle('is-active',isPdf)}
  if(pdfFooter){pdfFooter.hidden=!isPdf;pdfFooter.classList.toggle('is-active',isPdf)}
  if(pdfActions) pdfActions.hidden=!isPdf;
  APP_TABS.filter(n=>n!=='pdf').forEach(n=>{const el=$('#'+n+'Panel');if(!el)return;const active=name===n;el.hidden=!active;el.classList.toggle('is-active',active)});
  document.querySelectorAll('.appTab').forEach(b=>{const active=b.dataset.appTab===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});
  document.body.dataset.activeTab=name;
  try{sessionStorage.setItem('osama-active-tab',name)}catch{}
  if(name==='templates')renderTemplates();
  if(name==='tasks')renderTasks();
  if(name==='links')renderLinks();
  if(name==='queue')renderQueue();
  if(name==='composer')renderComposer();
  if(name==='handover')generateHandover();
  if(name==='home')renderDashboard();
  window.scrollTo({top:0,left:0,behavior:'auto'});
}
// Delegation keeps navigation working even if the header is re-rendered later.
document.querySelector('.appTabs')?.addEventListener('click',e=>{const b=e.target.closest('[data-app-tab]');if(b){e.preventDefault();setAppTab(b.dataset.appTab)}});

function placeholders(body){return [...new Set([...body.matchAll(/{{\s*([a-zA-Z0-9_ -]+)\s*}}/g)].map(m=>m[1].trim()))]}
function fillTemplate(t){let body=t.body;for(const key of placeholders(body)){const val=prompt(`Enter ${key.replace(/_/g,' ')}:`,'');if(val===null)return null;body=body.split('{{'+key+'}}').join(val);body=body.replace(new RegExp('{{\\s*'+key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s*}}','g'),val)}return body}
async function copyTemplate(t){if(!t)return;const text=fillTemplate(t);if(text===null)return;try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}const b=document.querySelector(`[data-copy-template="${t.id}"]`);if(b){b.textContent='✓ Copied';setTimeout(()=>b.textContent='⧉ Copy',1200)}}
function updateTemplateFilters(items){const sel=$('#templateCategory'),cur=sel.value,cats=[...new Set(items.map(x=>x.category).filter(Boolean))].sort();sel.innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if(cats.includes(cur))sel.value=cur;$('#categorySuggestions').innerHTML=cats.map(c=>`<option value="${esc(c)}"></option>`).join('')}
function renderTemplates(){let all=loadTemplates();updateTemplateFilters(all);const q=$('#templateSearch').value.trim().toLowerCase(),cat=$('#templateCategory').value,fav=$('#favoritesOnly').checked;let items=all.filter(t=>(!q||(t.name+' '+t.category+' '+t.body).toLowerCase().includes(q))&&(!cat||t.category===cat)&&(!fav||t.favorite));items.sort((a,b)=>(Number(b.favorite)-Number(a.favorite))||((b.updatedAt||0)-(a.updatedAt||0)));$('#templateCards').innerHTML=items.length?items.map(t=>`<article class="templateCard"><div class="templateCardHead"><div><h3>${esc(t.name)}</h3><span class="categoryPill">${esc(t.category||'General')}</span></div><button class="starBtn ${t.favorite?'on':''}" data-fav-template="${t.id}" title="Favorite">${t.favorite?'★':'☆'}</button></div><pre>${esc(t.body)}</pre><div class="templateActions"><button class="primary" data-copy-template="${t.id}">⧉ Copy</button><button data-edit-template="${t.id}">✎ Edit</button><button data-dup-template="${t.id}">Duplicate</button><button class="dangerText" data-del-template="${t.id}">Delete</button></div></article>`).join(''):'<div class="emptyTemplates"><h3>No templates here yet</h3><p>Add your first reusable email reply.</p></div>';
document.querySelectorAll('[data-copy-template]').forEach(b=>b.onclick=()=>copyTemplate(loadTemplates().find(t=>t.id===b.dataset.copyTemplate)));document.querySelectorAll('[data-edit-template]').forEach(b=>b.onclick=()=>openTemplateModal(loadTemplates().find(t=>t.id===b.dataset.editTemplate)));document.querySelectorAll('[data-dup-template]').forEach(b=>b.onclick=()=>{const a=loadTemplates(),t=a.find(x=>x.id===b.dataset.dupTemplate);if(!t)return;a.unshift({...t,id:crypto.randomUUID(),name:t.name+' (Copy)',favorite:false,updatedAt:Date.now()});saveTemplates(a);renderTemplates()});document.querySelectorAll('[data-fav-template]').forEach(b=>b.onclick=()=>{const a=loadTemplates(),t=a.find(x=>x.id===b.dataset.favTemplate);if(t){t.favorite=!t.favorite;t.updatedAt=Date.now();saveTemplates(a);renderTemplates()}});document.querySelectorAll('[data-del-template]').forEach(b=>b.onclick=()=>{if(confirm('Delete this email template?')){saveTemplates(loadTemplates().filter(t=>t.id!==b.dataset.delTemplate));renderTemplates()}})}
function openTemplateModal(t=null){editingTemplateId=t?.id||null;$('#templateModalTitle').textContent=t?'Edit Template':'Add Template';$('#tplName').value=t?.name||'';$('#tplCategory').value=t?.category||'';$('#tplBody').value=t?.body||'';$('#templateModal').hidden=false;setTimeout(()=>$('#tplName').focus(),0)}
function closeTemplateModal(){$('#templateModal').hidden=true;editingTemplateId=null}
$('#addTemplate').onclick=()=>openTemplateModal();$('#closeTemplateModal').onclick=closeTemplateModal;$('#cancelTemplate').onclick=closeTemplateModal;$('#templateModal').onclick=e=>{if(e.target===$('#templateModal'))closeTemplateModal()};
$('#saveTemplate').onclick=()=>{const name=$('#tplName').value.trim(),body=$('#tplBody').value.trim(),category=$('#tplCategory').value.trim()||'General';if(!name){alert('Please add a template name.');return $('#tplName').focus()}if(!body){alert('Please add the email text.');return $('#tplBody').focus()}const a=loadTemplates(),now=Date.now();if(editingTemplateId){const t=a.find(x=>x.id===editingTemplateId);if(t)Object.assign(t,{name,body,category,updatedAt:now})}else a.unshift({id:crypto.randomUUID(),name,body,category,favorite:false,createdAt:now,updatedAt:now});saveTemplates(a);closeTemplateModal();renderTemplates()};
$('#templateSearch').oninput=renderTemplates;$('#templateCategory').onchange=renderTemplates;$('#favoritesOnly').onchange=renderTemplates;window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#templateModal').hidden)closeTemplateModal()});


// V9 workspace modules
const TASK_KEY='osama-automation-tasks-v1', LINK_KEY='osama-automation-links-v1', NOTES_KEY='osama-automation-notes-v1';
const todayKey=()=>new Date().toISOString().slice(0,10);
const readLocal=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const writeLocal=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let editingTaskId=null,editingLinkId=null;
function ensureRecurring(){const a=readLocal(TASK_KEY),today=todayKey();let changed=false;for(const t of [...a])if(t.recurring&&t.date!==today&&!a.some(x=>x.recurringSource===t.id&&x.date===today)){a.unshift({...t,id:crypto.randomUUID(),date:today,done:false,doneAt:null,recurring:false,recurringSource:t.recurringSource||t.id,createdAt:Date.now()});changed=true}if(changed)writeLocal(TASK_KEY,a)}
function renderTasks(){ensureRecurring();const all=readLocal(TASK_KEY),q=$('#taskSearch').value.trim().toLowerCase(),f=$('#taskFilter').value,today=todayKey();let items=all.filter(t=>(!q||(t.title+' '+(t.notes||'')).toLowerCase().includes(q))&&(f==='all'||(f==='done'?t.done:!t.done)));items.sort((a,b)=>(Number(a.done)-Number(b.done))||(Number(b.priority==='Urgent')-Number(a.priority==='Urgent'))||String(a.time||'99:99').localeCompare(String(b.time||'99:99')));const td=all.filter(t=>t.date===today),done=td.filter(t=>t.done).length;$('#taskProgress').innerHTML=`<b>${done} / ${td.length} completed today</b><div class="progressTrack"><i style="width:${td.length?done/td.length*100:0}%"></i></div>`;$('#taskList').innerHTML=items.length?items.map(t=>`<article class="listCard ${t.done?'done':''}"><button class="doneBtn" data-task-done="${t.id}" title="Mark ${t.done?'pending':'done'}">${t.done?'✓':'○'}</button><div class="grow"><b>${esc(t.title)}</b><div class="meta">${esc(t.date||'')} ${t.time?'• '+esc(t.time):''} • ${esc(t.priority||'Normal')}${t.recurring?' • ↻ Daily':''}</div>${t.notes?`<div class="cardNote">${esc(t.notes)}</div>`:''}</div><button data-task-edit="${t.id}">Edit</button><button class="dangerText" data-task-del="${t.id}">Delete</button></article>`).join(''):'<div class="emptyTemplates">No tasks match this view.</div>';document.querySelectorAll('[data-task-done]').forEach(b=>b.onclick=()=>{const a=readLocal(TASK_KEY),t=a.find(x=>x.id===b.dataset.taskDone);if(t){t.done=!t.done;t.doneAt=t.done?Date.now():null;writeLocal(TASK_KEY,a);renderTasks();renderDashboard()}});document.querySelectorAll('[data-task-edit]').forEach(b=>b.onclick=()=>openTask(readLocal(TASK_KEY).find(x=>x.id===b.dataset.taskEdit)));document.querySelectorAll('[data-task-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete this task?')){writeLocal(TASK_KEY,readLocal(TASK_KEY).filter(x=>x.id!==b.dataset.taskDel));renderTasks();renderDashboard()}})}
function openTask(t=null){editingTaskId=t?.id||null;$('#taskModalTitle').textContent=t?'Edit Task':'Add Task';$('#taskTitle').value=t?.title||'';$('#taskPriority').value=t?.priority||'Normal';$('#taskTime').value=t?.time||'';$('#taskRecurring').checked=!!t?.recurring;$('#taskNotes').value=t?.notes||'';$('#taskModal').hidden=false;setTimeout(()=>$('#taskTitle').focus(),0)}
$('#addTask').onclick=()=>openTask();$('#saveTask').onclick=()=>{const title=$('#taskTitle').value.trim();if(!title)return alert('Please add a task.');const a=readLocal(TASK_KEY),data={title,priority:$('#taskPriority').value,time:$('#taskTime').value,recurring:$('#taskRecurring').checked,notes:$('#taskNotes').value.trim(),date:todayKey(),updatedAt:Date.now()};if(editingTaskId){const t=a.find(x=>x.id===editingTaskId);if(t)Object.assign(t,data)}else a.unshift({id:crypto.randomUUID(),done:false,createdAt:Date.now(),...data});writeLocal(TASK_KEY,a);$('#taskModal').hidden=true;editingTaskId=null;renderTasks();renderDashboard()};$('#taskFilter').onchange=renderTasks;$('#taskSearch').oninput=renderTasks;$('#clearDone').onclick=()=>{if(confirm('Remove all completed tasks?')){writeLocal(TASK_KEY,readLocal(TASK_KEY).filter(t=>!t.done));renderTasks();renderDashboard()}};$('#carryTasks').onclick=()=>{const a=readLocal(TASK_KEY),today=todayKey();let n=0;for(const t of a)if(!t.done&&t.date!==today){t.date=today;n++}writeLocal(TASK_KEY,a);renderTasks();alert(n?`${n} task(s) moved to today.`:'No pending older tasks.')};
function renderLinks(){const q=$('#linkSearch').value.trim().toLowerCase();let a=readLocal(LINK_KEY).filter(x=>!q||(x.name+' '+x.url).toLowerCase().includes(q));a.sort((x,y)=>Number(y.favorite)-Number(x.favorite)||(y.updatedAt||0)-(x.updatedAt||0));$('#linkList').innerHTML=a.length?a.map(x=>`<article class="linkCard"><div class="grow"><b>${x.favorite?'★ ':''}${esc(x.name)}</b><div class="meta">${esc(x.url)}</div></div><a class="buttonLink primary" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Open</a><button data-link-edit="${x.id}">Edit</button><button class="dangerText" data-link-del="${x.id}">Delete</button></article>`).join(''):'<div class="emptyTemplates">No links saved yet.</div>';document.querySelectorAll('[data-link-edit]').forEach(b=>b.onclick=()=>openLink(readLocal(LINK_KEY).find(x=>x.id===b.dataset.linkEdit)));document.querySelectorAll('[data-link-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete this link?')){writeLocal(LINK_KEY,readLocal(LINK_KEY).filter(x=>x.id!==b.dataset.linkDel));renderLinks();renderDashboard()}})}
function openLink(x=null){editingLinkId=x?.id||null;$('#linkModalTitle').textContent=x?'Edit Link':'Add Link';$('#linkName').value=x?.name||'';$('#linkUrl').value=x?.url||'';$('#linkFavorite').checked=!!x?.favorite;$('#linkModal').hidden=false}
$('#addLink').onclick=()=>openLink();$('#saveLink').onclick=()=>{const name=$('#linkName').value.trim(),url=$('#linkUrl').value.trim();if(!name||!url)return alert('Please add a name and URL.');let u;try{u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw 0}catch{return alert('Please enter a valid http/https URL.')}const a=readLocal(LINK_KEY),data={name,url:u.href,favorite:$('#linkFavorite').checked,updatedAt:Date.now()};if(editingLinkId){const x=a.find(y=>y.id===editingLinkId);if(x)Object.assign(x,data)}else a.unshift({id:crypto.randomUUID(),createdAt:Date.now(),...data});writeLocal(LINK_KEY,a);$('#linkModal').hidden=true;editingLinkId=null;renderLinks();renderDashboard()};$('#linkSearch').oninput=renderLinks;
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{$('#'+b.dataset.close).hidden=true});
const notes=$('#quickNotes');notes.value=localStorage.getItem(NOTES_KEY)||'';let notesTimer;notes.oninput=()=>{clearTimeout(notesTimer);$('#notesStatus').textContent='Saving…';notesTimer=setTimeout(()=>{localStorage.setItem(NOTES_KEY,notes.value);$('#notesStatus').textContent='Saved locally';renderDashboard()},250)};$('#copyNotes').onclick=async()=>{try{await navigator.clipboard.writeText(notes.value)}catch{}$('#notesStatus').textContent='Copied'};$('#clearNotes').onclick=()=>{if(confirm('Clear quick notes?')){notes.value='';localStorage.removeItem(NOTES_KEY);$('#notesStatus').textContent='Cleared';renderDashboard()}};
function renderDashboard(){ensureRecurring();const a=readLocal(TASK_KEY),today=todayKey(),td=a.filter(t=>t.date===today),pending=td.filter(t=>!t.done),templates=loadTemplates(),links=readLocal(LINK_KEY),favs=links.filter(x=>x.favorite).slice(0,5);$('#dashboardGrid').innerHTML=`<article class="dashCard"><span>Today</span><strong>${td.filter(t=>t.done).length}/${td.length}</strong><p>tasks completed</p><button data-go="tasks">Open Daily Tasks</button></article><article class="dashCard"><span>Pending</span><strong>${pending.length}</strong><p>${pending.filter(t=>t.priority==='Urgent').length} urgent</p><button data-go="tasks">View pending</button></article><article class="dashCard"><span>Email templates</span><strong>${templates.length}</strong><p>${templates.filter(t=>t.favorite).length} favorites</p><button data-go="templates">Open Templates</button></article><article class="dashCard wide"><span>Favorite links</span>${favs.length?favs.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.name)}</a>`).join(''):'<p>No favorite links yet.</p>'}<button data-go="links">Manage Links</button></article><article class="dashCard wide"><span>Quick Notes</span><p>${esc((notes.value||'No notes saved.').slice(0,180))}</p><button data-go="notes">Open Notes</button></article>`;document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>setAppTab(b.dataset.go))}
$('#exportBackup').onclick=()=>{const includeSigs=confirm('Include saved signature images in this backup? Only do this for an authorised work device.');const keys=[TEMPLATE_KEY,TASK_KEY,LINK_KEY,NOTES_KEY];const data={version:9,createdAt:new Date().toISOString(),storage:{}};for(const k of keys)data.storage[k]=localStorage.getItem(k);if(includeSigs){for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&/sig|signature/i.test(k))data.storage[k]=localStorage.getItem(k)}}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='osama-automation-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};
$('#importBackup').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!d.storage||typeof d.storage!=='object')throw 0;if(!confirm('Import this backup and overwrite matching local workspace data?'))return;for(const [k,v] of Object.entries(d.storage))if(typeof v==='string')localStorage.setItem(k,v);notes.value=localStorage.getItem(NOTES_KEY)||'';renderTemplates();renderTasks();renderLinks();renderDashboard();alert('Backup restored.')}catch{alert('This does not look like a valid Osama Automation backup.')}finally{e.target.value=''}};
setAppTab('home');renderDashboard();

// V10 workflow modules - no login, cloud storage, or external-system integration.
const QUEUE_KEY='osama-automation-queue-v1', SNIPPET_KEY='osama-automation-snippets-v1', PREF_KEY='osama-automation-preferences-v1';
let editingCaseId=null,editingSnippetId=null,queueDueOnly=false,composerTemplateId='';
const checklistTemplates={external:['Referral checked','Required details checked','Payment route checked','PDF prepared','Referral sent','Tracker updated','Response received','Follow-up completed'],booking:['Request checked','Required details available','Availability checked','Booking completed','Confirmation prepared']};
const fmtDate=v=>{if(!v)return 'No follow-up';const d=new Date(v);return Number.isNaN(+d)?v:d.toLocaleString()};
function renderQueue(){const all=readLocal(QUEUE_KEY),q=$('#queueSearch').value.trim().toLowerCase(),st=$('#queueStatus').value,pr=$('#queuePriority').value,now=Date.now();let items=all.filter(c=>(!q||(c.title+' '+(c.notes||'')+' '+(c.owner||'')+' '+(c.modality||'')).toLowerCase().includes(q))&&(!st||c.status===st)&&(!pr||c.priority===pr)&&(!queueDueOnly||(c.status!=='Completed'&&c.followup&&new Date(c.followup).getTime()<=now)));items.sort((a,b)=>Number(a.status==='Completed')-Number(b.status==='Completed')||Number(b.priority==='Urgent')-Number(a.priority==='Urgent')||((a.followup?new Date(a.followup).getTime():Infinity)-(b.followup?new Date(b.followup).getTime():Infinity)));const open=all.filter(c=>c.status!=='Completed'),due=open.filter(c=>c.followup&&new Date(c.followup).getTime()<=now);$('#queueStats').innerHTML=`<b>${open.length} open • ${due.length} due/overdue • ${open.filter(c=>c.priority==='Urgent').length} urgent</b>`;$('#showDue').classList.toggle('active',queueDueOnly);$('#queueList').innerHTML=items.length?items.map(c=>{const dueNow=c.status!=='Completed'&&c.followup&&new Date(c.followup).getTime()<=now;const checks=c.checklist||[];const checked=checks.filter(x=>x.done).length;return `<article class="listCard queueCard ${dueNow?'overdue':''}"><div class="grow"><div class="queueTitle"><b>${esc(c.title)}</b><span class="statusPill">${esc(c.status)}</span>${c.priority==='Urgent'?'<span class="urgentPill">Urgent</span>':''}</div><div class="meta">${esc(c.modality||'General')} • Owner: ${esc(c.owner||'Unassigned')} • Follow-up: ${esc(fmtDate(c.followup))}${checks.length?` • Checklist ${checked}/${checks.length}`:''}</div>${c.notes?`<div class="cardNote">${esc(c.notes)}</div>`:''}${checks.length?`<div class="caseChecks">${checks.map((x,i)=>`<label><input type="checkbox" data-case-check="${c.id}:${i}" ${x.done?'checked':''}> ${esc(x.label)}</label>`).join('')}</div>`:''}</div><button data-case-follow="${c.id}">Follow-up</button><button data-case-edit="${c.id}">Edit</button><button data-case-complete="${c.id}">${c.status==='Completed'?'Reopen':'✓ Complete'}</button><button class="dangerText" data-case-del="${c.id}">Delete</button></article>`}).join(''):'<div class="emptyTemplates">No cases match this view.</div>';
 document.querySelectorAll('[data-case-check]').forEach(el=>el.onchange=()=>{const [id,idx]=el.dataset.caseCheck.split(':');const a=readLocal(QUEUE_KEY),c=a.find(x=>x.id===id);if(c?.checklist?.[+idx]){c.checklist[+idx].done=el.checked;c.updatedAt=Date.now();writeLocal(QUEUE_KEY,a);renderQueue();renderDashboard()}});document.querySelectorAll('[data-case-edit]').forEach(b=>b.onclick=()=>openCase(readLocal(QUEUE_KEY).find(x=>x.id===b.dataset.caseEdit)));document.querySelectorAll('[data-case-follow]').forEach(b=>b.onclick=()=>{const a=readLocal(QUEUE_KEY),c=a.find(x=>x.id===b.dataset.caseFollow);if(!c)return;const v=prompt('Next follow-up date/time (YYYY-MM-DD HH:MM):',c.followup?c.followup.replace('T',' '):'');if(v===null)return;const parsed=v.trim()?new Date(v.trim().replace(' ','T')):null;if(v.trim()&&Number.isNaN(+parsed))return alert('Invalid date/time.');c.followup=parsed?new Date(parsed.getTime()-parsed.getTimezoneOffset()*60000).toISOString().slice(0,16):'';c.updatedAt=Date.now();writeLocal(QUEUE_KEY,a);renderQueue();renderDashboard()});document.querySelectorAll('[data-case-complete]').forEach(b=>b.onclick=()=>{const a=readLocal(QUEUE_KEY),c=a.find(x=>x.id===b.dataset.caseComplete);if(c){c.status=c.status==='Completed'?'New':'Completed';c.completedAt=c.status==='Completed'?Date.now():null;c.updatedAt=Date.now();writeLocal(QUEUE_KEY,a);renderQueue();renderDashboard()}});document.querySelectorAll('[data-case-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete this case?')){writeLocal(QUEUE_KEY,readLocal(QUEUE_KEY).filter(x=>x.id!==b.dataset.caseDel));renderQueue();renderDashboard()}})}
function openCase(c=null){editingCaseId=c?.id||null;$('#caseModalTitle').textContent=c?'Edit Case':'Add Case';$('#caseTitle').value=c?.title||'';$('#caseStatus').value=c?.status||'New';$('#casePriority').value=c?.priority||'Normal';$('#caseOwner').value=c?.owner||'';$('#caseModality').value=c?.modality||'General';$('#caseFollowup').value=c?.followup||'';$('#caseNotes').value=c?.notes||'';$('#caseChecklistType').value=c?.checklistType||'';$('#caseModal').hidden=false;setTimeout(()=>$('#caseTitle').focus(),0)}
$('#addCase').onclick=()=>openCase();$('#saveCase').onclick=()=>{const title=$('#caseTitle').value.trim();if(!title)return alert('Add a reference or description.');const a=readLocal(QUEUE_KEY),type=$('#caseChecklistType').value,data={title,status:$('#caseStatus').value,priority:$('#casePriority').value,owner:$('#caseOwner').value.trim(),modality:$('#caseModality').value,followup:$('#caseFollowup').value,notes:$('#caseNotes').value.trim(),checklistType:type,updatedAt:Date.now()};if(editingCaseId){const c=a.find(x=>x.id===editingCaseId);if(c){const oldType=c.checklistType;Object.assign(c,data);if(type!==oldType)c.checklist=(checklistTemplates[type]||[]).map(label=>({label,done:false}))}}else a.unshift({id:crypto.randomUUID(),createdAt:Date.now(),checklist:(checklistTemplates[type]||[]).map(label=>({label,done:false})),...data});writeLocal(QUEUE_KEY,a);$('#caseModal').hidden=true;editingCaseId=null;renderQueue();renderDashboard()};$('#queueSearch').oninput=renderQueue;$('#queueStatus').onchange=renderQueue;$('#queuePriority').onchange=renderQueue;$('#showDue').onclick=()=>{queueDueOnly=!queueDueOnly;renderQueue()};
function loadSnippets(){return readLocal(SNIPPET_KEY)}function renderComposer(){const templates=loadTemplates();$('#composerTemplate').innerHTML='<option value="">Choose template…</option>'+templates.map(t=>`<option value="${t.id}" ${t.id===composerTemplateId?'selected':''}>${esc(t.name)}</option>`).join('');renderSnippets();if(composerTemplateId)loadComposerTemplate(composerTemplateId)}
function composePlaceholders(body){return [...new Set([...body.matchAll(/{{\s*([^{}]+?)\s*}}/g)].map(m=>m[1].trim()))]}
function loadComposerTemplate(id){composerTemplateId=id;const t=loadTemplates().find(x=>x.id===id);if(!t){$('#composerFields').innerHTML='';return}const fields=composePlaceholders(t.body);$('#composerFields').innerHTML=fields.map(k=>`<label>${esc(k.replaceAll('_',' '))}<input data-compose-field="${esc(k)}" placeholder="${esc(k.replaceAll('_',' '))}"></label>`).join('');$('#composerPreview').value=t.body;document.querySelectorAll('[data-compose-field]').forEach(i=>i.oninput=updateComposerPreview)}
function updateComposerPreview(){const t=loadTemplates().find(x=>x.id===composerTemplateId);if(!t)return;let body=t.body;document.querySelectorAll('[data-compose-field]').forEach(i=>{body=body.replace(new RegExp('{{\\s*'+i.dataset.composeField.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s*}}','g'),i.value)});$('#composerPreview').value=body}
$('#composerTemplate').onchange=e=>{composerTemplateId=e.target.value;loadComposerTemplate(composerTemplateId)};$('#copySubject').onclick=()=>copyText($('#composerSubject').value,'Subject copied');$('#copyBody').onclick=()=>copyText($('#composerPreview').value,'Email copied');$('#clearComposer').onclick=()=>{$('#composerSubject').value='';$('#composerPreview').value='';composerTemplateId='';$('#composerTemplate').value='';$('#composerFields').innerHTML=''};
async function copyText(v,msg){if(!v)return;try{await navigator.clipboard.writeText(v);alert(msg)}catch{alert('Copy failed. Select the text and copy manually.')}}
function renderSnippets(){const a=loadSnippets();$('#snippetList').innerHTML=a.length?a.map(s=>`<div class="snippet"><button data-snippet-use="${s.id}" title="Insert snippet">+ ${esc(s.name)}</button><button data-snippet-edit="${s.id}">Edit</button><button class="dangerText" data-snippet-del="${s.id}">×</button></div>`).join(''):'<div class="mini">No snippets saved yet.</div>';document.querySelectorAll('[data-snippet-use]').forEach(b=>b.onclick=()=>{const s=loadSnippets().find(x=>x.id===b.dataset.snippetUse);if(s){const ta=$('#composerPreview'),start=ta.selectionStart??ta.value.length;ta.value=ta.value.slice(0,start)+(start?'\n':'')+s.body+ta.value.slice(start);ta.focus()}});document.querySelectorAll('[data-snippet-edit]').forEach(b=>b.onclick=()=>openSnippet(loadSnippets().find(x=>x.id===b.dataset.snippetEdit)));document.querySelectorAll('[data-snippet-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete snippet?')){writeLocal(SNIPPET_KEY,loadSnippets().filter(x=>x.id!==b.dataset.snippetDel));renderSnippets()}})}
function openSnippet(s=null){editingSnippetId=s?.id||null;$('#snippetModalTitle').textContent=s?'Edit Snippet':'Add Snippet';$('#snippetName').value=s?.name||'';$('#snippetBody').value=s?.body||'';$('#snippetModal').hidden=false}$('#addSnippet').onclick=()=>openSnippet();$('#saveSnippet').onclick=()=>{const name=$('#snippetName').value.trim(),body=$('#snippetBody').value.trim();if(!name||!body)return alert('Add a name and text.');const a=loadSnippets();if(editingSnippetId){const s=a.find(x=>x.id===editingSnippetId);if(s)Object.assign(s,{name,body,updatedAt:Date.now()})}else a.unshift({id:crypto.randomUUID(),name,body,createdAt:Date.now()});writeLocal(SNIPPET_KEY,a);$('#snippetModal').hidden=true;editingSnippetId=null;renderSnippets()};
function generateHandover(){const q=readLocal(QUEUE_KEY),open=q.filter(c=>c.status!=='Completed'),due=open.filter(c=>c.followup&&new Date(c.followup).getTime()<=Date.now()),tasks=readLocal(TASK_KEY).filter(t=>t.date===todayKey()),pending=tasks.filter(t=>!t.done);const byStatus={};open.forEach(c=>byStatus[c.status]=(byStatus[c.status]||0)+1);const lines=[`Shift Handover - ${new Date().toLocaleString()}`,'',`Work queue: ${open.length} open | ${due.length} due/overdue | ${open.filter(c=>c.priority==='Urgent').length} urgent`,...Object.entries(byStatus).map(([k,v])=>`- ${k}: ${v}`),'',`Daily tasks: ${tasks.filter(t=>t.done).length}/${tasks.length} completed | ${pending.length} pending`];if(due.length){lines.push('','Due / overdue follow-ups:');due.slice(0,20).forEach(c=>lines.push(`- ${c.title} | ${c.status} | ${c.modality||'General'} | ${fmtDate(c.followup)}`))}if(pending.length){lines.push('','Pending tasks:');pending.slice(0,20).forEach(t=>lines.push(`- ${t.priority==='Urgent'?'URGENT - ':''}${t.title}${t.time?' @ '+t.time:''}`))}$('#handoverText').value=lines.join('\n')}$('#generateHandover').onclick=generateHandover;$('#copyHandover').onclick=()=>copyText($('#handoverText').value,'Handover copied');
// Universal search across local non-PDF workspace data.
let searchTimer;$('#globalSearch').oninput=e=>{clearTimeout(searchTimer);const q=e.target.value.trim().toLowerCase();if(!q){$('#searchModal').hidden=true;return}searchTimer=setTimeout(()=>{const results=[];loadTemplates().forEach(x=>{if((x.name+' '+x.body+' '+x.category).toLowerCase().includes(q))results.push({type:'Template',title:x.name,tab:'templates'})});readLocal(TASK_KEY).forEach(x=>{if((x.title+' '+(x.notes||'')).toLowerCase().includes(q))results.push({type:'Task',title:x.title,tab:'tasks'})});readLocal(LINK_KEY).forEach(x=>{if((x.name+' '+x.url).toLowerCase().includes(q))results.push({type:'Link',title:x.name,tab:'links'})});readLocal(QUEUE_KEY).forEach(x=>{if((x.title+' '+(x.notes||'')+' '+(x.owner||'')).toLowerCase().includes(q))results.push({type:'Case',title:x.title,tab:'queue'})});loadSnippets().forEach(x=>{if((x.name+' '+x.body).toLowerCase().includes(q))results.push({type:'Snippet',title:x.name,tab:'composer'})});$('#searchResults').innerHTML=results.length?results.slice(0,50).map((r,i)=>`<button class="searchResult" data-search-go="${r.tab}"><b>${esc(r.type)}</b><span>${esc(r.title)}</span></button>`).join(''):'<div class="emptyTemplates">No matches.</div>';$('#searchModal').hidden=false;document.querySelectorAll('[data-search-go]').forEach(b=>b.onclick=()=>{$('#searchModal').hidden=true;$('#globalSearch').value='';setAppTab(b.dataset.searchGo)})},180)};
// Theme and density preferences.
function applyPrefs(){const p=readLocal(PREF_KEY,{});document.body.classList.toggle('dark',!!p.dark);document.body.classList.toggle('compact',!!p.compact);$('#themeToggle').textContent=p.dark?'☀':'◐';$('#compactToggle').classList.toggle('active',!!p.compact)}function togglePref(k){const p=readLocal(PREF_KEY,{});p[k]=!p[k];writeLocal(PREF_KEY,p);applyPrefs()}$('#themeToggle').onclick=()=>togglePref('dark');$('#compactToggle').onclick=()=>togglePref('compact');applyPrefs();
// Optional human pre-save checklist; all boxes must be acknowledged before export.
const rawPdfSave=$('#save').onclick;$('#save').onclick=()=>{if(!pdfBytes)return;document.querySelectorAll('.pdfReview').forEach(x=>x.checked=false);$('#pdfCheckModal').hidden=false};$('#confirmPdfSave').onclick=()=>{if(![...document.querySelectorAll('.pdfReview')].every(x=>x.checked))return alert('Please review and tick each item before saving.');$('#pdfCheckModal').hidden=true;rawPdfSave?.()};
// Extend backups to V10 workspace keys.
const oldExportBackup=$('#exportBackup').onclick;$('#exportBackup').onclick=()=>{const includeSigs=confirm('Include saved signature images in this backup? Only do this for an authorised work device.');const keys=[TEMPLATE_KEY,TASK_KEY,LINK_KEY,NOTES_KEY,QUEUE_KEY,SNIPPET_KEY,PREF_KEY];const data={version:10,createdAt:new Date().toISOString(),storage:{}};for(const k of keys)data.storage[k]=localStorage.getItem(k);if(includeSigs){for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&/sig|signature/i.test(k))data.storage[k]=localStorage.getItem(k)}}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='osama-automation-v10-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};
// V10 dashboard extension.
const baseRenderDashboard=renderDashboard;renderDashboard=function(){baseRenderDashboard();const q=readLocal(QUEUE_KEY),open=q.filter(c=>c.status!=='Completed'),due=open.filter(c=>c.followup&&new Date(c.followup).getTime()<=Date.now());$('#dashboardGrid').insertAdjacentHTML('afterbegin',`<article class="dashCard"><span>Work Queue</span><strong>${open.length}</strong><p>${due.length} due/overdue • ${open.filter(c=>c.priority==='Urgent').length} urgent</p><button data-go-v10="queue">Open Queue</button></article><article class="dashCard"><span>Quick compose</span><strong>✉</strong><p>Templates + placeholders + snippets</p><button data-go-v10="composer">Compose Email</button></article><article class="dashCard"><span>Shift handover</span><strong>↗</strong><p>Generate outstanding-work summary</p><button data-go-v10="handover">Generate Handover</button></article>`);document.querySelectorAll('[data-go-v10]').forEach(b=>b.onclick=()=>setAppTab(b.dataset.goV10))};
// Modal backdrop close and Escape safety for new dialogs.
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.hidden=true}));window.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelectorAll('.modal:not([hidden])').forEach(m=>m.hidden=true)}});
renderDashboard();

// Restore the last module safely; PDF is the fallback.
let initialTab='pdf';try{initialTab=sessionStorage.getItem('osama-active-tab')||'pdf'}catch{}setAppTab(initialTab);
